services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=umeda
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=golang_twitter
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://umeda:password@postgres:5432/golang_twitter?sslmode=disable
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - .:/golang_twitter
      - /golang_twitter/tmp

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres: