services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    environment:
      - ENV=${ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis_server:6379
    depends_on:
      - postgres
      - redis_server
    ports:
      - 8080:8080
    volumes:
      - .:/golang_twitter
      - /golang_twitter/tmp
  redis_server:
    container_name: redis_server
    image: redis:latest
    # 明示的にパスワードなしで起動する設定を追加（安全策）
    command: ["redis-server", "--protected-mode", "no"]
    ports:
      - "16379:6379"

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres:
