// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"
)

const createUserActivation = `-- name: CreateUserActivation :one
INSERT INTO user_activations (
  user_id,
  token,
  expired_at
) VALUES (
  $1, $2, $3
) RETURNING id, user_id, token, expired_at, created_at
`

type CreateUserActivationParams struct {
	UserID    int32     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expired_at"`
}

func (q *Queries) CreateUserActivation(ctx context.Context, arg CreateUserActivationParams) (UserActivation, error) {
	row := q.queryRow(ctx, q.createUserActivationStmt, createUserActivation, arg.UserID, arg.Token, arg.ExpiredAt)
	var i UserActivation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserActivation = `-- name: DeleteUserActivation :exec
DELETE FROM user_activations
WHERE token = $1
`

func (q *Queries) DeleteUserActivation(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteUserActivationStmt, deleteUserActivation, token)
	return err
}

const getUserActivationByToken = `-- name: GetUserActivationByToken :one
SELECT id, user_id, token, expired_at, created_at FROM user_activations
WHERE token = $1 AND expired_at > NOW()
LIMIT 1
`

func (q *Queries) GetUserActivationByToken(ctx context.Context, token string) (UserActivation, error) {
	row := q.queryRow(ctx, q.getUserActivationByTokenStmt, getUserActivationByToken, token)
	var i UserActivation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}
