// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package db

import (
	"context"
	"time"
)

const countBookmarksByTweetID = `-- name: CountBookmarksByTweetID :one
SELECT COUNT(*)::bigint AS bookmark_count
FROM bookmarks
WHERE tweet_id = $1
`

func (q *Queries) CountBookmarksByTweetID(ctx context.Context, tweetID int32) (int64, error) {
	row := q.queryRow(ctx, q.countBookmarksByTweetIDStmt, countBookmarksByTweetID, tweetID)
	var bookmark_count int64
	err := row.Scan(&bookmark_count)
	return bookmark_count, err
}

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (
  user_id,
  tweet_id
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, tweet_id) DO NOTHING
RETURNING id, user_id, tweet_id, created_at
`

type CreateBookmarkParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.queryRow(ctx, q.createBookmarkStmt, createBookmark, arg.UserID, arg.TweetID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TweetID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1 AND tweet_id = $2
`

type DeleteBookmarkParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.exec(ctx, q.deleteBookmarkStmt, deleteBookmark, arg.UserID, arg.TweetID)
	return err
}

const existsBookmark = `-- name: ExistsBookmark :one
SELECT EXISTS(
  SELECT 1
  FROM bookmarks
  WHERE user_id = $1 AND tweet_id = $2
) AS exists
`

type ExistsBookmarkParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) ExistsBookmark(ctx context.Context, arg ExistsBookmarkParams) (bool, error) {
	row := q.queryRow(ctx, q.existsBookmarkStmt, existsBookmark, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBookmarksByUserId = `-- name: GetBookmarksByUserId :many
SELECT
  b.id,
  b.user_id,
  b.tweet_id,
  b.created_at,
  t.content
FROM bookmarks b
INNER JOIN tweets t ON t.id = b.tweet_id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
`

type GetBookmarksByUserIdRow struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	TweetID   int32     `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
	Content   string    `json:"content"`
}

func (q *Queries) GetBookmarksByUserId(ctx context.Context, userID int32) ([]GetBookmarksByUserIdRow, error) {
	rows, err := q.query(ctx, q.getBookmarksByUserIdStmt, getBookmarksByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookmarksByUserIdRow{}
	for rows.Next() {
		var i GetBookmarksByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TweetID,
			&i.CreatedAt,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
