// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package db

import (
	"context"
)

const countBookmarksByTweetID = `-- name: CountBookmarksByTweetID :one
SELECT COUNT(*)::bigint AS bookmark_count
FROM bookmarks
WHERE tweet_id = $1
`

func (q *Queries) CountBookmarksByTweetID(ctx context.Context, tweetID int32) (int64, error) {
	row := q.queryRow(ctx, q.countBookmarksByTweetIDStmt, countBookmarksByTweetID, tweetID)
	var bookmark_count int64
	err := row.Scan(&bookmark_count)
	return bookmark_count, err
}

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (
  user_id,
  tweet_id
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, tweet_id) DO NOTHING
RETURNING id, user_id, tweet_id, created_at
`

type CreateBookmarkParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.queryRow(ctx, q.createBookmarkStmt, createBookmark, arg.UserID, arg.TweetID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TweetID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1 AND tweet_id = $2
`

type DeleteBookmarkParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.exec(ctx, q.deleteBookmarkStmt, deleteBookmark, arg.UserID, arg.TweetID)
	return err
}

const existsBookmark = `-- name: ExistsBookmark :one
SELECT EXISTS(
  SELECT 1
  FROM bookmarks
  WHERE user_id = $1 AND tweet_id = $2
) AS exists
`

type ExistsBookmarkParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) ExistsBookmark(ctx context.Context, arg ExistsBookmarkParams) (bool, error) {
	row := q.queryRow(ctx, q.existsBookmarkStmt, existsBookmark, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
