// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const countCommentsByTweetID = `-- name: CountCommentsByTweetID :one
SELECT COUNT(*)::bigint AS comment_count
FROM comments
WHERE tweet_id = $1
`

func (q *Queries) CountCommentsByTweetID(ctx context.Context, tweetID int32) (int64, error) {
	row := q.queryRow(ctx, q.countCommentsByTweetIDStmt, countCommentsByTweetID, tweetID)
	var comment_count int64
	err := row.Scan(&comment_count)
	return comment_count, err
}

const countCommentsByTweetIDs = `-- name: CountCommentsByTweetIDs :many
SELECT tweet_id, COUNT(*)::bigint AS comment_count
FROM comments
WHERE tweet_id = ANY($1::int[])
GROUP BY tweet_id
`

type CountCommentsByTweetIDsRow struct {
	TweetID      int32 `json:"tweet_id"`
	CommentCount int64 `json:"comment_count"`
}

func (q *Queries) CountCommentsByTweetIDs(ctx context.Context, dollar_1 []int32) ([]CountCommentsByTweetIDsRow, error) {
	rows, err := q.query(ctx, q.countCommentsByTweetIDsStmt, countCommentsByTweetIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCommentsByTweetIDsRow{}
	for rows.Next() {
		var i CountCommentsByTweetIDsRow
		if err := rows.Scan(&i.TweetID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  user_id,
  tweet_id
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, tweet_id) DO NOTHING
RETURNING id, user_id, tweet_id, created_at
`

type CreateCommentParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.queryRow(ctx, q.createCommentStmt, createComment, arg.UserID, arg.TweetID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TweetID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE user_id = $1 AND tweet_id = $2
`

type DeleteCommentParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.exec(ctx, q.deleteCommentStmt, deleteComment, arg.UserID, arg.TweetID)
	return err
}

const existsComment = `-- name: ExistsComment :one
SELECT EXISTS(
  SELECT 1
  FROM comments
  WHERE user_id = $1 AND tweet_id = $2
) AS exists
`

type ExistsCommentParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) ExistsComment(ctx context.Context, arg ExistsCommentParams) (bool, error) {
	row := q.queryRow(ctx, q.existsCommentStmt, existsComment, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
