// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countBookmarksByTweetIDStmt, err = db.PrepareContext(ctx, countBookmarksByTweetID); err != nil {
		return nil, fmt.Errorf("error preparing query CountBookmarksByTweetID: %w", err)
	}
	if q.countCommentsByTweetIDStmt, err = db.PrepareContext(ctx, countCommentsByTweetID); err != nil {
		return nil, fmt.Errorf("error preparing query CountCommentsByTweetID: %w", err)
	}
	if q.countCommentsByTweetIDsStmt, err = db.PrepareContext(ctx, countCommentsByTweetIDs); err != nil {
		return nil, fmt.Errorf("error preparing query CountCommentsByTweetIDs: %w", err)
	}
	if q.countLikesByTweetIDStmt, err = db.PrepareContext(ctx, countLikesByTweetID); err != nil {
		return nil, fmt.Errorf("error preparing query CountLikesByTweetID: %w", err)
	}
	if q.countLikesByTweetIDsStmt, err = db.PrepareContext(ctx, countLikesByTweetIDs); err != nil {
		return nil, fmt.Errorf("error preparing query CountLikesByTweetIDs: %w", err)
	}
	if q.countRetweetsByTweetIDStmt, err = db.PrepareContext(ctx, countRetweetsByTweetID); err != nil {
		return nil, fmt.Errorf("error preparing query CountRetweetsByTweetID: %w", err)
	}
	if q.countRetweetsByTweetIDsStmt, err = db.PrepareContext(ctx, countRetweetsByTweetIDs); err != nil {
		return nil, fmt.Errorf("error preparing query CountRetweetsByTweetIDs: %w", err)
	}
	if q.createBookmarkStmt, err = db.PrepareContext(ctx, createBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBookmark: %w", err)
	}
	if q.createCommentStmt, err = db.PrepareContext(ctx, createComment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateComment: %w", err)
	}
	if q.createFollowStmt, err = db.PrepareContext(ctx, createFollow); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFollow: %w", err)
	}
	if q.createGroupStmt, err = db.PrepareContext(ctx, createGroup); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGroup: %w", err)
	}
	if q.createGroupMemberStmt, err = db.PrepareContext(ctx, createGroupMember); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGroupMember: %w", err)
	}
	if q.createLikeStmt, err = db.PrepareContext(ctx, createLike); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLike: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createRetweetStmt, err = db.PrepareContext(ctx, createRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRetweet: %w", err)
	}
	if q.createTweetStmt, err = db.PrepareContext(ctx, createTweet); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTweet: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserActivationStmt, err = db.PrepareContext(ctx, createUserActivation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserActivation: %w", err)
	}
	if q.createUserProfileStmt, err = db.PrepareContext(ctx, createUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserProfile: %w", err)
	}
	if q.deleteBookmarkStmt, err = db.PrepareContext(ctx, deleteBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookmark: %w", err)
	}
	if q.deleteCommentStmt, err = db.PrepareContext(ctx, deleteComment); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteComment: %w", err)
	}
	if q.deleteFollowStmt, err = db.PrepareContext(ctx, deleteFollow); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFollow: %w", err)
	}
	if q.deleteLikeStmt, err = db.PrepareContext(ctx, deleteLike); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLike: %w", err)
	}
	if q.deleteRetweetStmt, err = db.PrepareContext(ctx, deleteRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRetweet: %w", err)
	}
	if q.deleteTweetStmt, err = db.PrepareContext(ctx, deleteTweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTweet: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteUserActivationStmt, err = db.PrepareContext(ctx, deleteUserActivation); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserActivation: %w", err)
	}
	if q.existsBookmarkStmt, err = db.PrepareContext(ctx, existsBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsBookmark: %w", err)
	}
	if q.existsCommentStmt, err = db.PrepareContext(ctx, existsComment); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsComment: %w", err)
	}
	if q.existsGroupMemberStmt, err = db.PrepareContext(ctx, existsGroupMember); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsGroupMember: %w", err)
	}
	if q.existsLikeStmt, err = db.PrepareContext(ctx, existsLike); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsLike: %w", err)
	}
	if q.existsRetweetStmt, err = db.PrepareContext(ctx, existsRetweet); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsRetweet: %w", err)
	}
	if q.getAllTweetsStmt, err = db.PrepareContext(ctx, getAllTweets); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTweets: %w", err)
	}
	if q.getAllTweetsWithCursorStmt, err = db.PrepareContext(ctx, getAllTweetsWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTweetsWithCursor: %w", err)
	}
	if q.getBookmarksByUserIdStmt, err = db.PrepareContext(ctx, getBookmarksByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookmarksByUserId: %w", err)
	}
	if q.getCommentsByTweetIDWithCursorStmt, err = db.PrepareContext(ctx, getCommentsByTweetIDWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetCommentsByTweetIDWithCursor: %w", err)
	}
	if q.getFollowersByUserIdWithCursorStmt, err = db.PrepareContext(ctx, getFollowersByUserIdWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetFollowersByUserIdWithCursor: %w", err)
	}
	if q.getFollowingByUserIdWithCursorStmt, err = db.PrepareContext(ctx, getFollowingByUserIdWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetFollowingByUserIdWithCursor: %w", err)
	}
	if q.getGroupByIDStmt, err = db.PrepareContext(ctx, getGroupByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupByID: %w", err)
	}
	if q.getGroupsByMemberUserIDStmt, err = db.PrepareContext(ctx, getGroupsByMemberUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupsByMemberUserID: %w", err)
	}
	if q.getGroupsByUserIDStmt, err = db.PrepareContext(ctx, getGroupsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupsByUserID: %w", err)
	}
	if q.getMessagesByGroupIDStmt, err = db.PrepareContext(ctx, getMessagesByGroupID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessagesByGroupID: %w", err)
	}
	if q.getTweetByIDStmt, err = db.PrepareContext(ctx, getTweetByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetByID: %w", err)
	}
	if q.getTweetsByIDsStmt, err = db.PrepareContext(ctx, getTweetsByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetsByIDs: %w", err)
	}
	if q.getTweetsByUserIDStmt, err = db.PrepareContext(ctx, getTweetsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetsByUserID: %w", err)
	}
	if q.getTweetsByUserIDWithCursorStmt, err = db.PrepareContext(ctx, getTweetsByUserIDWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetsByUserIDWithCursor: %w", err)
	}
	if q.getUserActivationByTokenStmt, err = db.PrepareContext(ctx, getUserActivationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserActivationByToken: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserDetailByUserIDStmt, err = db.PrepareContext(ctx, getUserDetailByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserDetailByUserID: %w", err)
	}
	if q.getUserLikesWithCursorStmt, err = db.PrepareContext(ctx, getUserLikesWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserLikesWithCursor: %w", err)
	}
	if q.getUserProfileByUserIDStmt, err = db.PrepareContext(ctx, getUserProfileByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserProfileByUserID: %w", err)
	}
	if q.getUserRetweetsWithCursorStmt, err = db.PrepareContext(ctx, getUserRetweetsWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRetweetsWithCursor: %w", err)
	}
	if q.updateUserIsActiveStmt, err = db.PrepareContext(ctx, updateUserIsActive); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserIsActive: %w", err)
	}
	if q.updateUserProfileStmt, err = db.PrepareContext(ctx, updateUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfile: %w", err)
	}
	if q.updateUserProfileImageStmt, err = db.PrepareContext(ctx, updateUserProfileImage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfileImage: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countBookmarksByTweetIDStmt != nil {
		if cerr := q.countBookmarksByTweetIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBookmarksByTweetIDStmt: %w", cerr)
		}
	}
	if q.countCommentsByTweetIDStmt != nil {
		if cerr := q.countCommentsByTweetIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCommentsByTweetIDStmt: %w", cerr)
		}
	}
	if q.countCommentsByTweetIDsStmt != nil {
		if cerr := q.countCommentsByTweetIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCommentsByTweetIDsStmt: %w", cerr)
		}
	}
	if q.countLikesByTweetIDStmt != nil {
		if cerr := q.countLikesByTweetIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countLikesByTweetIDStmt: %w", cerr)
		}
	}
	if q.countLikesByTweetIDsStmt != nil {
		if cerr := q.countLikesByTweetIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countLikesByTweetIDsStmt: %w", cerr)
		}
	}
	if q.countRetweetsByTweetIDStmt != nil {
		if cerr := q.countRetweetsByTweetIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countRetweetsByTweetIDStmt: %w", cerr)
		}
	}
	if q.countRetweetsByTweetIDsStmt != nil {
		if cerr := q.countRetweetsByTweetIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countRetweetsByTweetIDsStmt: %w", cerr)
		}
	}
	if q.createBookmarkStmt != nil {
		if cerr := q.createBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookmarkStmt: %w", cerr)
		}
	}
	if q.createCommentStmt != nil {
		if cerr := q.createCommentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCommentStmt: %w", cerr)
		}
	}
	if q.createFollowStmt != nil {
		if cerr := q.createFollowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFollowStmt: %w", cerr)
		}
	}
	if q.createGroupStmt != nil {
		if cerr := q.createGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGroupStmt: %w", cerr)
		}
	}
	if q.createGroupMemberStmt != nil {
		if cerr := q.createGroupMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGroupMemberStmt: %w", cerr)
		}
	}
	if q.createLikeStmt != nil {
		if cerr := q.createLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLikeStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createRetweetStmt != nil {
		if cerr := q.createRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRetweetStmt: %w", cerr)
		}
	}
	if q.createTweetStmt != nil {
		if cerr := q.createTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTweetStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserActivationStmt != nil {
		if cerr := q.createUserActivationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserActivationStmt: %w", cerr)
		}
	}
	if q.createUserProfileStmt != nil {
		if cerr := q.createUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserProfileStmt: %w", cerr)
		}
	}
	if q.deleteBookmarkStmt != nil {
		if cerr := q.deleteBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookmarkStmt: %w", cerr)
		}
	}
	if q.deleteCommentStmt != nil {
		if cerr := q.deleteCommentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCommentStmt: %w", cerr)
		}
	}
	if q.deleteFollowStmt != nil {
		if cerr := q.deleteFollowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFollowStmt: %w", cerr)
		}
	}
	if q.deleteLikeStmt != nil {
		if cerr := q.deleteLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLikeStmt: %w", cerr)
		}
	}
	if q.deleteRetweetStmt != nil {
		if cerr := q.deleteRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRetweetStmt: %w", cerr)
		}
	}
	if q.deleteTweetStmt != nil {
		if cerr := q.deleteTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTweetStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteUserActivationStmt != nil {
		if cerr := q.deleteUserActivationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserActivationStmt: %w", cerr)
		}
	}
	if q.existsBookmarkStmt != nil {
		if cerr := q.existsBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsBookmarkStmt: %w", cerr)
		}
	}
	if q.existsCommentStmt != nil {
		if cerr := q.existsCommentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsCommentStmt: %w", cerr)
		}
	}
	if q.existsGroupMemberStmt != nil {
		if cerr := q.existsGroupMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsGroupMemberStmt: %w", cerr)
		}
	}
	if q.existsLikeStmt != nil {
		if cerr := q.existsLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsLikeStmt: %w", cerr)
		}
	}
	if q.existsRetweetStmt != nil {
		if cerr := q.existsRetweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsRetweetStmt: %w", cerr)
		}
	}
	if q.getAllTweetsStmt != nil {
		if cerr := q.getAllTweetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTweetsStmt: %w", cerr)
		}
	}
	if q.getAllTweetsWithCursorStmt != nil {
		if cerr := q.getAllTweetsWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTweetsWithCursorStmt: %w", cerr)
		}
	}
	if q.getBookmarksByUserIdStmt != nil {
		if cerr := q.getBookmarksByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookmarksByUserIdStmt: %w", cerr)
		}
	}
	if q.getCommentsByTweetIDWithCursorStmt != nil {
		if cerr := q.getCommentsByTweetIDWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCommentsByTweetIDWithCursorStmt: %w", cerr)
		}
	}
	if q.getFollowersByUserIdWithCursorStmt != nil {
		if cerr := q.getFollowersByUserIdWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFollowersByUserIdWithCursorStmt: %w", cerr)
		}
	}
	if q.getFollowingByUserIdWithCursorStmt != nil {
		if cerr := q.getFollowingByUserIdWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFollowingByUserIdWithCursorStmt: %w", cerr)
		}
	}
	if q.getGroupByIDStmt != nil {
		if cerr := q.getGroupByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupByIDStmt: %w", cerr)
		}
	}
	if q.getGroupsByMemberUserIDStmt != nil {
		if cerr := q.getGroupsByMemberUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupsByMemberUserIDStmt: %w", cerr)
		}
	}
	if q.getGroupsByUserIDStmt != nil {
		if cerr := q.getGroupsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupsByUserIDStmt: %w", cerr)
		}
	}
	if q.getMessagesByGroupIDStmt != nil {
		if cerr := q.getMessagesByGroupIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessagesByGroupIDStmt: %w", cerr)
		}
	}
	if q.getTweetByIDStmt != nil {
		if cerr := q.getTweetByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetByIDStmt: %w", cerr)
		}
	}
	if q.getTweetsByIDsStmt != nil {
		if cerr := q.getTweetsByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsByIDsStmt: %w", cerr)
		}
	}
	if q.getTweetsByUserIDStmt != nil {
		if cerr := q.getTweetsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsByUserIDStmt: %w", cerr)
		}
	}
	if q.getTweetsByUserIDWithCursorStmt != nil {
		if cerr := q.getTweetsByUserIDWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsByUserIDWithCursorStmt: %w", cerr)
		}
	}
	if q.getUserActivationByTokenStmt != nil {
		if cerr := q.getUserActivationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserActivationByTokenStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserDetailByUserIDStmt != nil {
		if cerr := q.getUserDetailByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserDetailByUserIDStmt: %w", cerr)
		}
	}
	if q.getUserLikesWithCursorStmt != nil {
		if cerr := q.getUserLikesWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserLikesWithCursorStmt: %w", cerr)
		}
	}
	if q.getUserProfileByUserIDStmt != nil {
		if cerr := q.getUserProfileByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserProfileByUserIDStmt: %w", cerr)
		}
	}
	if q.getUserRetweetsWithCursorStmt != nil {
		if cerr := q.getUserRetweetsWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRetweetsWithCursorStmt: %w", cerr)
		}
	}
	if q.updateUserIsActiveStmt != nil {
		if cerr := q.updateUserIsActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserIsActiveStmt: %w", cerr)
		}
	}
	if q.updateUserProfileStmt != nil {
		if cerr := q.updateUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileStmt: %w", cerr)
		}
	}
	if q.updateUserProfileImageStmt != nil {
		if cerr := q.updateUserProfileImageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileImageStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	countBookmarksByTweetIDStmt        *sql.Stmt
	countCommentsByTweetIDStmt         *sql.Stmt
	countCommentsByTweetIDsStmt        *sql.Stmt
	countLikesByTweetIDStmt            *sql.Stmt
	countLikesByTweetIDsStmt           *sql.Stmt
	countRetweetsByTweetIDStmt         *sql.Stmt
	countRetweetsByTweetIDsStmt        *sql.Stmt
	createBookmarkStmt                 *sql.Stmt
	createCommentStmt                  *sql.Stmt
	createFollowStmt                   *sql.Stmt
	createGroupStmt                    *sql.Stmt
	createGroupMemberStmt              *sql.Stmt
	createLikeStmt                     *sql.Stmt
	createMessageStmt                  *sql.Stmt
	createRetweetStmt                  *sql.Stmt
	createTweetStmt                    *sql.Stmt
	createUserStmt                     *sql.Stmt
	createUserActivationStmt           *sql.Stmt
	createUserProfileStmt              *sql.Stmt
	deleteBookmarkStmt                 *sql.Stmt
	deleteCommentStmt                  *sql.Stmt
	deleteFollowStmt                   *sql.Stmt
	deleteLikeStmt                     *sql.Stmt
	deleteRetweetStmt                  *sql.Stmt
	deleteTweetStmt                    *sql.Stmt
	deleteUserStmt                     *sql.Stmt
	deleteUserActivationStmt           *sql.Stmt
	existsBookmarkStmt                 *sql.Stmt
	existsCommentStmt                  *sql.Stmt
	existsGroupMemberStmt              *sql.Stmt
	existsLikeStmt                     *sql.Stmt
	existsRetweetStmt                  *sql.Stmt
	getAllTweetsStmt                   *sql.Stmt
	getAllTweetsWithCursorStmt         *sql.Stmt
	getBookmarksByUserIdStmt           *sql.Stmt
	getCommentsByTweetIDWithCursorStmt *sql.Stmt
	getFollowersByUserIdWithCursorStmt *sql.Stmt
	getFollowingByUserIdWithCursorStmt *sql.Stmt
	getGroupByIDStmt                   *sql.Stmt
	getGroupsByMemberUserIDStmt        *sql.Stmt
	getGroupsByUserIDStmt              *sql.Stmt
	getMessagesByGroupIDStmt           *sql.Stmt
	getTweetByIDStmt                   *sql.Stmt
	getTweetsByIDsStmt                 *sql.Stmt
	getTweetsByUserIDStmt              *sql.Stmt
	getTweetsByUserIDWithCursorStmt    *sql.Stmt
	getUserActivationByTokenStmt       *sql.Stmt
	getUserByEmailStmt                 *sql.Stmt
	getUserDetailByUserIDStmt          *sql.Stmt
	getUserLikesWithCursorStmt         *sql.Stmt
	getUserProfileByUserIDStmt         *sql.Stmt
	getUserRetweetsWithCursorStmt      *sql.Stmt
	updateUserIsActiveStmt             *sql.Stmt
	updateUserProfileStmt              *sql.Stmt
	updateUserProfileImageStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		countBookmarksByTweetIDStmt:        q.countBookmarksByTweetIDStmt,
		countCommentsByTweetIDStmt:         q.countCommentsByTweetIDStmt,
		countCommentsByTweetIDsStmt:        q.countCommentsByTweetIDsStmt,
		countLikesByTweetIDStmt:            q.countLikesByTweetIDStmt,
		countLikesByTweetIDsStmt:           q.countLikesByTweetIDsStmt,
		countRetweetsByTweetIDStmt:         q.countRetweetsByTweetIDStmt,
		countRetweetsByTweetIDsStmt:        q.countRetweetsByTweetIDsStmt,
		createBookmarkStmt:                 q.createBookmarkStmt,
		createCommentStmt:                  q.createCommentStmt,
		createFollowStmt:                   q.createFollowStmt,
		createGroupStmt:                    q.createGroupStmt,
		createGroupMemberStmt:              q.createGroupMemberStmt,
		createLikeStmt:                     q.createLikeStmt,
		createMessageStmt:                  q.createMessageStmt,
		createRetweetStmt:                  q.createRetweetStmt,
		createTweetStmt:                    q.createTweetStmt,
		createUserStmt:                     q.createUserStmt,
		createUserActivationStmt:           q.createUserActivationStmt,
		createUserProfileStmt:              q.createUserProfileStmt,
		deleteBookmarkStmt:                 q.deleteBookmarkStmt,
		deleteCommentStmt:                  q.deleteCommentStmt,
		deleteFollowStmt:                   q.deleteFollowStmt,
		deleteLikeStmt:                     q.deleteLikeStmt,
		deleteRetweetStmt:                  q.deleteRetweetStmt,
		deleteTweetStmt:                    q.deleteTweetStmt,
		deleteUserStmt:                     q.deleteUserStmt,
		deleteUserActivationStmt:           q.deleteUserActivationStmt,
		existsBookmarkStmt:                 q.existsBookmarkStmt,
		existsCommentStmt:                  q.existsCommentStmt,
		existsGroupMemberStmt:              q.existsGroupMemberStmt,
		existsLikeStmt:                     q.existsLikeStmt,
		existsRetweetStmt:                  q.existsRetweetStmt,
		getAllTweetsStmt:                   q.getAllTweetsStmt,
		getAllTweetsWithCursorStmt:         q.getAllTweetsWithCursorStmt,
		getBookmarksByUserIdStmt:           q.getBookmarksByUserIdStmt,
		getCommentsByTweetIDWithCursorStmt: q.getCommentsByTweetIDWithCursorStmt,
		getFollowersByUserIdWithCursorStmt: q.getFollowersByUserIdWithCursorStmt,
		getFollowingByUserIdWithCursorStmt: q.getFollowingByUserIdWithCursorStmt,
		getGroupByIDStmt:                   q.getGroupByIDStmt,
		getGroupsByMemberUserIDStmt:        q.getGroupsByMemberUserIDStmt,
		getGroupsByUserIDStmt:              q.getGroupsByUserIDStmt,
		getMessagesByGroupIDStmt:           q.getMessagesByGroupIDStmt,
		getTweetByIDStmt:                   q.getTweetByIDStmt,
		getTweetsByIDsStmt:                 q.getTweetsByIDsStmt,
		getTweetsByUserIDStmt:              q.getTweetsByUserIDStmt,
		getTweetsByUserIDWithCursorStmt:    q.getTweetsByUserIDWithCursorStmt,
		getUserActivationByTokenStmt:       q.getUserActivationByTokenStmt,
		getUserByEmailStmt:                 q.getUserByEmailStmt,
		getUserDetailByUserIDStmt:          q.getUserDetailByUserIDStmt,
		getUserLikesWithCursorStmt:         q.getUserLikesWithCursorStmt,
		getUserProfileByUserIDStmt:         q.getUserProfileByUserIDStmt,
		getUserRetweetsWithCursorStmt:      q.getUserRetweetsWithCursorStmt,
		updateUserIsActiveStmt:             q.updateUserIsActiveStmt,
		updateUserProfileStmt:              q.updateUserProfileStmt,
		updateUserProfileImageStmt:         q.updateUserProfileImageStmt,
	}
}
