// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countBookmarksByTweetIDStmt, err = db.PrepareContext(ctx, countBookmarksByTweetID); err != nil {
		return nil, fmt.Errorf("error preparing query CountBookmarksByTweetID: %w", err)
	}
	if q.countLikesByTweetIDStmt, err = db.PrepareContext(ctx, countLikesByTweetID); err != nil {
		return nil, fmt.Errorf("error preparing query CountLikesByTweetID: %w", err)
	}
	if q.createBookmarkStmt, err = db.PrepareContext(ctx, createBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBookmark: %w", err)
	}
	if q.createGroupStmt, err = db.PrepareContext(ctx, createGroup); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGroup: %w", err)
	}
	if q.createLikeStmt, err = db.PrepareContext(ctx, createLike); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLike: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createTweetStmt, err = db.PrepareContext(ctx, createTweet); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTweet: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserActivationStmt, err = db.PrepareContext(ctx, createUserActivation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserActivation: %w", err)
	}
	if q.deleteBookmarkStmt, err = db.PrepareContext(ctx, deleteBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBookmark: %w", err)
	}
	if q.deleteLikeStmt, err = db.PrepareContext(ctx, deleteLike); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLike: %w", err)
	}
	if q.deleteTweetStmt, err = db.PrepareContext(ctx, deleteTweet); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTweet: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteUserActivationStmt, err = db.PrepareContext(ctx, deleteUserActivation); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserActivation: %w", err)
	}
	if q.existsBookmarkStmt, err = db.PrepareContext(ctx, existsBookmark); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsBookmark: %w", err)
	}
	if q.existsLikeStmt, err = db.PrepareContext(ctx, existsLike); err != nil {
		return nil, fmt.Errorf("error preparing query ExistsLike: %w", err)
	}
	if q.getAllTweetsStmt, err = db.PrepareContext(ctx, getAllTweets); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllTweets: %w", err)
	}
	if q.getBookmarksByUserIdStmt, err = db.PrepareContext(ctx, getBookmarksByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query GetBookmarksByUserId: %w", err)
	}
	if q.getGroupByIDStmt, err = db.PrepareContext(ctx, getGroupByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupByID: %w", err)
	}
	if q.getGroupsByUserIDStmt, err = db.PrepareContext(ctx, getGroupsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupsByUserID: %w", err)
	}
	if q.getMessagesByGroupIDStmt, err = db.PrepareContext(ctx, getMessagesByGroupID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessagesByGroupID: %w", err)
	}
	if q.getTweetByIDStmt, err = db.PrepareContext(ctx, getTweetByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetByID: %w", err)
	}
	if q.getTweetsByUserIDStmt, err = db.PrepareContext(ctx, getTweetsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetsByUserID: %w", err)
	}
	if q.getTweetsByUserIDWithCursorStmt, err = db.PrepareContext(ctx, getTweetsByUserIDWithCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetTweetsByUserIDWithCursor: %w", err)
	}
	if q.getUserActivationByTokenStmt, err = db.PrepareContext(ctx, getUserActivationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserActivationByToken: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserDetailByUserIDStmt, err = db.PrepareContext(ctx, getUserDetailByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserDetailByUserID: %w", err)
	}
	if q.updateUserIsActiveStmt, err = db.PrepareContext(ctx, updateUserIsActive); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserIsActive: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countBookmarksByTweetIDStmt != nil {
		if cerr := q.countBookmarksByTweetIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBookmarksByTweetIDStmt: %w", cerr)
		}
	}
	if q.countLikesByTweetIDStmt != nil {
		if cerr := q.countLikesByTweetIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countLikesByTweetIDStmt: %w", cerr)
		}
	}
	if q.createBookmarkStmt != nil {
		if cerr := q.createBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBookmarkStmt: %w", cerr)
		}
	}
	if q.createGroupStmt != nil {
		if cerr := q.createGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGroupStmt: %w", cerr)
		}
	}
	if q.createLikeStmt != nil {
		if cerr := q.createLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLikeStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createTweetStmt != nil {
		if cerr := q.createTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTweetStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserActivationStmt != nil {
		if cerr := q.createUserActivationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserActivationStmt: %w", cerr)
		}
	}
	if q.deleteBookmarkStmt != nil {
		if cerr := q.deleteBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBookmarkStmt: %w", cerr)
		}
	}
	if q.deleteLikeStmt != nil {
		if cerr := q.deleteLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLikeStmt: %w", cerr)
		}
	}
	if q.deleteTweetStmt != nil {
		if cerr := q.deleteTweetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTweetStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteUserActivationStmt != nil {
		if cerr := q.deleteUserActivationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserActivationStmt: %w", cerr)
		}
	}
	if q.existsBookmarkStmt != nil {
		if cerr := q.existsBookmarkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsBookmarkStmt: %w", cerr)
		}
	}
	if q.existsLikeStmt != nil {
		if cerr := q.existsLikeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing existsLikeStmt: %w", cerr)
		}
	}
	if q.getAllTweetsStmt != nil {
		if cerr := q.getAllTweetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllTweetsStmt: %w", cerr)
		}
	}
	if q.getBookmarksByUserIdStmt != nil {
		if cerr := q.getBookmarksByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBookmarksByUserIdStmt: %w", cerr)
		}
	}
	if q.getGroupByIDStmt != nil {
		if cerr := q.getGroupByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupByIDStmt: %w", cerr)
		}
	}
	if q.getGroupsByUserIDStmt != nil {
		if cerr := q.getGroupsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupsByUserIDStmt: %w", cerr)
		}
	}
	if q.getMessagesByGroupIDStmt != nil {
		if cerr := q.getMessagesByGroupIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessagesByGroupIDStmt: %w", cerr)
		}
	}
	if q.getTweetByIDStmt != nil {
		if cerr := q.getTweetByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetByIDStmt: %w", cerr)
		}
	}
	if q.getTweetsByUserIDStmt != nil {
		if cerr := q.getTweetsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsByUserIDStmt: %w", cerr)
		}
	}
	if q.getTweetsByUserIDWithCursorStmt != nil {
		if cerr := q.getTweetsByUserIDWithCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTweetsByUserIDWithCursorStmt: %w", cerr)
		}
	}
	if q.getUserActivationByTokenStmt != nil {
		if cerr := q.getUserActivationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserActivationByTokenStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserDetailByUserIDStmt != nil {
		if cerr := q.getUserDetailByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserDetailByUserIDStmt: %w", cerr)
		}
	}
	if q.updateUserIsActiveStmt != nil {
		if cerr := q.updateUserIsActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserIsActiveStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	countBookmarksByTweetIDStmt     *sql.Stmt
	countLikesByTweetIDStmt         *sql.Stmt
	createBookmarkStmt              *sql.Stmt
	createGroupStmt                 *sql.Stmt
	createLikeStmt                  *sql.Stmt
	createMessageStmt               *sql.Stmt
	createTweetStmt                 *sql.Stmt
	createUserStmt                  *sql.Stmt
	createUserActivationStmt        *sql.Stmt
	deleteBookmarkStmt              *sql.Stmt
	deleteLikeStmt                  *sql.Stmt
	deleteTweetStmt                 *sql.Stmt
	deleteUserStmt                  *sql.Stmt
	deleteUserActivationStmt        *sql.Stmt
	existsBookmarkStmt              *sql.Stmt
	existsLikeStmt                  *sql.Stmt
	getAllTweetsStmt                *sql.Stmt
	getBookmarksByUserIdStmt        *sql.Stmt
	getGroupByIDStmt                *sql.Stmt
	getGroupsByUserIDStmt           *sql.Stmt
	getMessagesByGroupIDStmt        *sql.Stmt
	getTweetByIDStmt                *sql.Stmt
	getTweetsByUserIDStmt           *sql.Stmt
	getTweetsByUserIDWithCursorStmt *sql.Stmt
	getUserActivationByTokenStmt    *sql.Stmt
	getUserByEmailStmt              *sql.Stmt
	getUserDetailByUserIDStmt       *sql.Stmt
	updateUserIsActiveStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		countBookmarksByTweetIDStmt:     q.countBookmarksByTweetIDStmt,
		countLikesByTweetIDStmt:         q.countLikesByTweetIDStmt,
		createBookmarkStmt:              q.createBookmarkStmt,
		createGroupStmt:                 q.createGroupStmt,
		createLikeStmt:                  q.createLikeStmt,
		createMessageStmt:               q.createMessageStmt,
		createTweetStmt:                 q.createTweetStmt,
		createUserStmt:                  q.createUserStmt,
		createUserActivationStmt:        q.createUserActivationStmt,
		deleteBookmarkStmt:              q.deleteBookmarkStmt,
		deleteLikeStmt:                  q.deleteLikeStmt,
		deleteTweetStmt:                 q.deleteTweetStmt,
		deleteUserStmt:                  q.deleteUserStmt,
		deleteUserActivationStmt:        q.deleteUserActivationStmt,
		existsBookmarkStmt:              q.existsBookmarkStmt,
		existsLikeStmt:                  q.existsLikeStmt,
		getAllTweetsStmt:                q.getAllTweetsStmt,
		getBookmarksByUserIdStmt:        q.getBookmarksByUserIdStmt,
		getGroupByIDStmt:                q.getGroupByIDStmt,
		getGroupsByUserIDStmt:           q.getGroupsByUserIDStmt,
		getMessagesByGroupIDStmt:        q.getMessagesByGroupIDStmt,
		getTweetByIDStmt:                q.getTweetByIDStmt,
		getTweetsByUserIDStmt:           q.getTweetsByUserIDStmt,
		getTweetsByUserIDWithCursorStmt: q.getTweetsByUserIDWithCursorStmt,
		getUserActivationByTokenStmt:    q.getUserActivationByTokenStmt,
		getUserByEmailStmt:              q.getUserByEmailStmt,
		getUserDetailByUserIDStmt:       q.getUserDetailByUserIDStmt,
		updateUserIsActiveStmt:          q.updateUserIsActiveStmt,
	}
}
