// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserActivationStmt, err = db.PrepareContext(ctx, createUserActivation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserActivation: %w", err)
	}
	if q.deleteUserActivationStmt, err = db.PrepareContext(ctx, deleteUserActivation); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserActivation: %w", err)
	}
	if q.getUserActivationByTokenStmt, err = db.PrepareContext(ctx, getUserActivationByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserActivationByToken: %w", err)
	}
	if q.updateUserIsActiveStmt, err = db.PrepareContext(ctx, updateUserIsActive); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserIsActive: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserActivationStmt != nil {
		if cerr := q.createUserActivationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserActivationStmt: %w", cerr)
		}
	}
	if q.deleteUserActivationStmt != nil {
		if cerr := q.deleteUserActivationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserActivationStmt: %w", cerr)
		}
	}
	if q.getUserActivationByTokenStmt != nil {
		if cerr := q.getUserActivationByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserActivationByTokenStmt: %w", cerr)
		}
	}
	if q.updateUserIsActiveStmt != nil {
		if cerr := q.updateUserIsActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserIsActiveStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	createUserStmt               *sql.Stmt
	createUserActivationStmt     *sql.Stmt
	deleteUserActivationStmt     *sql.Stmt
	getUserActivationByTokenStmt *sql.Stmt
	updateUserIsActiveStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		createUserStmt:               q.createUserStmt,
		createUserActivationStmt:     q.createUserActivationStmt,
		deleteUserActivationStmt:     q.deleteUserActivationStmt,
		getUserActivationByTokenStmt: q.getUserActivationByTokenStmt,
		updateUserIsActiveStmt:       q.updateUserIsActiveStmt,
	}
}
