// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follows.sql

package db

import (
	"context"
)

const createFollow = `-- name: CreateFollow :one
INSERT INTO follows (
  user_id,
  followed_user_id
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, followed_user_id) DO NOTHING
RETURNING id, user_id, followed_user_id, created_at
`

type CreateFollowParams struct {
	UserID         int32 `json:"user_id"`
	FollowedUserID int32 `json:"followed_user_id"`
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (Follow, error) {
	row := q.queryRow(ctx, q.createFollowStmt, createFollow, arg.UserID, arg.FollowedUserID)
	var i Follow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FollowedUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows
WHERE user_id = $1 AND followed_user_id = $2
`

type DeleteFollowParams struct {
	UserID         int32 `json:"user_id"`
	FollowedUserID int32 `json:"followed_user_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.exec(ctx, q.deleteFollowStmt, deleteFollow, arg.UserID, arg.FollowedUserID)
	return err
}

const getFollowersByUserIdWithCursor = `-- name: GetFollowersByUserIdWithCursor :many
SELECT id, user_id, followed_user_id, created_at
FROM follows
WHERE followed_user_id = $1
  AND (CASE WHEN $2 = 0 THEN true ELSE id < $2 END)
ORDER BY id DESC
LIMIT $3
`

type GetFollowersByUserIdWithCursorParams struct {
	FollowedUserID int32       `json:"followed_user_id"`
	Column2        interface{} `json:"column_2"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) GetFollowersByUserIdWithCursor(ctx context.Context, arg GetFollowersByUserIdWithCursorParams) ([]Follow, error) {
	rows, err := q.query(ctx, q.getFollowersByUserIdWithCursorStmt, getFollowersByUserIdWithCursor, arg.FollowedUserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Follow{}
	for rows.Next() {
		var i Follow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FollowedUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingByUserIdWithCursor = `-- name: GetFollowingByUserIdWithCursor :many
SELECT id, user_id, followed_user_id, created_at
FROM follows
WHERE user_id = $1
  AND (CASE WHEN $2 = 0 THEN true ELSE id < $2 END)
ORDER BY id DESC
LIMIT $3
`

type GetFollowingByUserIdWithCursorParams struct {
	UserID  int32       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetFollowingByUserIdWithCursor(ctx context.Context, arg GetFollowingByUserIdWithCursorParams) ([]Follow, error) {
	rows, err := q.query(ctx, q.getFollowingByUserIdWithCursorStmt, getFollowingByUserIdWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Follow{}
	for rows.Next() {
		var i Follow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FollowedUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
