// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
  name,
  user_id
) VALUES (
  $1, $2
)
RETURNING id, name, user_id, created_at
`

type CreateGroupParams struct {
	Name   string `json:"name"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.queryRow(ctx, q.createGroupStmt, createGroup, arg.Name, arg.UserID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, user_id, created_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int32) (Group, error) {
	row := q.queryRow(ctx, q.getGroupByIDStmt, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupsByUserID = `-- name: GetGroupsByUserID :many
SELECT id, name, user_id, created_at
FROM groups
WHERE user_id = $1
ORDER BY id DESC
`

func (q *Queries) GetGroupsByUserID(ctx context.Context, userID int32) ([]Group, error) {
	rows, err := q.query(ctx, q.getGroupsByUserIDStmt, getGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
