// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_members.sql

package db

import (
	"context"
	"time"
)

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (
  group_id,
  user_id
) VALUES (
  $1, $2
)
RETURNING group_id, user_id, created_at
`

type CreateGroupMemberParams struct {
	GroupID int32 `json:"group_id"`
	UserID  int32 `json:"user_id"`
}

type CreateGroupMemberRow struct {
	GroupID   int32     `json:"group_id"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (CreateGroupMemberRow, error) {
	row := q.queryRow(ctx, q.createGroupMemberStmt, createGroupMember, arg.GroupID, arg.UserID)
	var i CreateGroupMemberRow
	err := row.Scan(&i.GroupID, &i.UserID, &i.CreatedAt)
	return i, err
}
