// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_members.sql

package db

import (
	"context"
	"database/sql"
)

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (
  group_id,
  user_id,
  role,
  status,
  invited_by,
  accepted_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (group_id, user_id) DO NOTHING
RETURNING id, group_id, user_id, role, status, invited_by, accepted_at, created_at
`

type CreateGroupMemberParams struct {
	GroupID    int32             `json:"group_id"`
	UserID     int32             `json:"user_id"`
	Role       GroupMemberRole   `json:"role"`
	Status     GroupMemberStatus `json:"status"`
	InvitedBy  sql.NullInt32     `json:"invited_by"`
	AcceptedAt sql.NullTime      `json:"accepted_at"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.queryRow(ctx, q.createGroupMemberStmt, createGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.InvitedBy,
		arg.AcceptedAt,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}
