// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_tweets.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createImageTweet = `-- name: CreateImageTweet :one
INSERT INTO image_tweets (
  user_id,
  image_url
) VALUES (
  $1, $2
) RETURNING id, user_id, image_url, created_at, updated_at
`

type CreateImageTweetParams struct {
	UserID   int32  `json:"user_id"`
	ImageUrl string `json:"image_url"`
}

func (q *Queries) CreateImageTweet(ctx context.Context, arg CreateImageTweetParams) (ImageTweet, error) {
	row := q.queryRow(ctx, q.createImageTweetStmt, createImageTweet, arg.UserID, arg.ImageUrl)
	var i ImageTweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImageTweet = `-- name: DeleteImageTweet :exec
DELETE FROM image_tweets
WHERE id = $1 AND user_id = $2
`

type DeleteImageTweetParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteImageTweet(ctx context.Context, arg DeleteImageTweetParams) error {
	_, err := q.exec(ctx, q.deleteImageTweetStmt, deleteImageTweet, arg.ID, arg.UserID)
	return err
}

const getAllImageTweets = `-- name: GetAllImageTweets :many
SELECT id, user_id, image_url, created_at, updated_at
FROM image_tweets
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetAllImageTweets(ctx context.Context, limit int32) ([]ImageTweet, error) {
	rows, err := q.query(ctx, q.getAllImageTweetsStmt, getAllImageTweets, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageTweet{}
	for rows.Next() {
		var i ImageTweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageTweetByID = `-- name: GetImageTweetByID :one
SELECT id, user_id, image_url, created_at, updated_at
FROM image_tweets
WHERE id = $1
`

func (q *Queries) GetImageTweetByID(ctx context.Context, id int32) (ImageTweet, error) {
	row := q.queryRow(ctx, q.getImageTweetByIDStmt, getImageTweetByID, id)
	var i ImageTweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageTweetsByIDs = `-- name: GetImageTweetsByIDs :many
SELECT id, user_id, image_url, created_at, updated_at
FROM image_tweets
WHERE id = ANY($1::int[])
`

func (q *Queries) GetImageTweetsByIDs(ctx context.Context, dollar_1 []int32) ([]ImageTweet, error) {
	rows, err := q.query(ctx, q.getImageTweetsByIDsStmt, getImageTweetsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageTweet{}
	for rows.Next() {
		var i ImageTweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageTweetsByUserID = `-- name: GetImageTweetsByUserID :many
SELECT id, user_id, image_url, created_at, updated_at
FROM image_tweets
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetImageTweetsByUserID(ctx context.Context, userID int32) ([]ImageTweet, error) {
	rows, err := q.query(ctx, q.getImageTweetsByUserIDStmt, getImageTweetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageTweet{}
	for rows.Next() {
		var i ImageTweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageTweetsByUserIDWithCursor = `-- name: GetImageTweetsByUserIDWithCursor :many
SELECT id, user_id, image_url, created_at, updated_at
FROM image_tweets
WHERE user_id = $1
  AND (CASE WHEN $2 = 0 THEN true ELSE id < $2 END)
ORDER BY id DESC
LIMIT $3
`

type GetImageTweetsByUserIDWithCursorParams struct {
	UserID  int32       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetImageTweetsByUserIDWithCursor(ctx context.Context, arg GetImageTweetsByUserIDWithCursorParams) ([]ImageTweet, error) {
	rows, err := q.query(ctx, q.getImageTweetsByUserIDWithCursorStmt, getImageTweetsByUserIDWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageTweet{}
	for rows.Next() {
		var i ImageTweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
