// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package db

import (
	"context"
)

const countLikesByTweetID = `-- name: CountLikesByTweetID :one
SELECT COUNT(*)::bigint AS like_count
FROM likes
WHERE tweet_id = $1
`

func (q *Queries) CountLikesByTweetID(ctx context.Context, tweetID int32) (int64, error) {
	row := q.queryRow(ctx, q.countLikesByTweetIDStmt, countLikesByTweetID, tweetID)
	var like_count int64
	err := row.Scan(&like_count)
	return like_count, err
}

const createLike = `-- name: CreateLike :one
INSERT INTO likes (
  user_id,
  tweet_id
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, tweet_id) DO NOTHING
RETURNING id, user_id, tweet_id, created_at
`

type CreateLikeParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.queryRow(ctx, q.createLikeStmt, createLike, arg.UserID, arg.TweetID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TweetID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE user_id = $1 AND tweet_id = $2
`

type DeleteLikeParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.exec(ctx, q.deleteLikeStmt, deleteLike, arg.UserID, arg.TweetID)
	return err
}

const existsLike = `-- name: ExistsLike :one
SELECT EXISTS(
  SELECT 1
  FROM likes
  WHERE user_id = $1 AND tweet_id = $2
) AS exists
`

type ExistsLikeParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) ExistsLike(ctx context.Context, arg ExistsLikeParams) (bool, error) {
	row := q.queryRow(ctx, q.existsLikeStmt, existsLike, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
