// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const countLikesByTweetID = `-- name: CountLikesByTweetID :one
SELECT COUNT(*)::bigint AS like_count
FROM likes
WHERE tweet_id = $1
`

func (q *Queries) CountLikesByTweetID(ctx context.Context, tweetID int32) (int64, error) {
	row := q.queryRow(ctx, q.countLikesByTweetIDStmt, countLikesByTweetID, tweetID)
	var like_count int64
	err := row.Scan(&like_count)
	return like_count, err
}

const countLikesByTweetIDs = `-- name: CountLikesByTweetIDs :many
SELECT tweet_id, COUNT(*)::bigint AS like_count
FROM likes
WHERE tweet_id = ANY($1::int[])
GROUP BY tweet_id
`

type CountLikesByTweetIDsRow struct {
	TweetID   int32 `json:"tweet_id"`
	LikeCount int64 `json:"like_count"`
}

func (q *Queries) CountLikesByTweetIDs(ctx context.Context, dollar_1 []int32) ([]CountLikesByTweetIDsRow, error) {
	rows, err := q.query(ctx, q.countLikesByTweetIDsStmt, countLikesByTweetIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLikesByTweetIDsRow{}
	for rows.Next() {
		var i CountLikesByTweetIDsRow
		if err := rows.Scan(&i.TweetID, &i.LikeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createLike = `-- name: CreateLike :one
INSERT INTO likes (
  user_id,
  tweet_id
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, tweet_id) DO NOTHING
RETURNING id, user_id, tweet_id, created_at
`

type CreateLikeParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.queryRow(ctx, q.createLikeStmt, createLike, arg.UserID, arg.TweetID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TweetID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE user_id = $1 AND tweet_id = $2
`

type DeleteLikeParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.exec(ctx, q.deleteLikeStmt, deleteLike, arg.UserID, arg.TweetID)
	return err
}

const existsLike = `-- name: ExistsLike :one
SELECT EXISTS(
  SELECT 1
  FROM likes
  WHERE user_id = $1 AND tweet_id = $2
) AS exists
`

type ExistsLikeParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) ExistsLike(ctx context.Context, arg ExistsLikeParams) (bool, error) {
	row := q.queryRow(ctx, q.existsLikeStmt, existsLike, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserLikesWithCursor = `-- name: GetUserLikesWithCursor :many
SELECT id, user_id, tweet_id, created_at
FROM likes
WHERE user_id = $1
  AND (CASE WHEN $2 = 0 THEN true ELSE id < $2 END)
ORDER BY id DESC
LIMIT $3
`

type GetUserLikesWithCursorParams struct {
	UserID  int32       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetUserLikesWithCursor(ctx context.Context, arg GetUserLikesWithCursorParams) ([]Like, error) {
	rows, err := q.query(ctx, q.getUserLikesWithCursorStmt, getUserLikesWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Like{}
	for rows.Next() {
		var i Like
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TweetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
