// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  user_id,
  group_id,
  content
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, group_id, content, created_at
`

type CreateMessageParams struct {
	UserID  int32  `json:"user_id"`
	GroupID int32  `json:"group_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage, arg.UserID, arg.GroupID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByGroupID = `-- name: GetMessagesByGroupID :many
SELECT id, user_id, group_id, content, created_at
FROM messages
WHERE group_id = $1
ORDER BY id DESC
`

func (q *Queries) GetMessagesByGroupID(ctx context.Context, groupID int32) ([]Message, error) {
	rows, err := q.query(ctx, q.getMessagesByGroupIDStmt, getMessagesByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
