// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Bookmark struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	TweetID   int32     `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Follow struct {
	ID             int32     `json:"id"`
	UserID         int32     `json:"user_id"`
	FollowedUserID int32     `json:"followed_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Group struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupMember struct {
	UserID    int32     `json:"user_id"`
	GroupID   int32     `json:"group_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Like struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	TweetID   int32     `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	GroupID   int32     `json:"group_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Retweet struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	TweetID   int32     `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Tweet struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Content   string    `json:"content"`
	ImageUrl  string    `json:"image_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserActivation struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expired_at"`
	CreatedAt time.Time `json:"created_at"`
}

type UserProfile struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Name      string    `json:"name"`
	Bio       string    `json:"bio"`
	Location  string    `json:"location"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
