// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type GroupMemberRole string

const (
	GroupMemberRoleAdmin  GroupMemberRole = "admin"
	GroupMemberRoleMember GroupMemberRole = "member"
)

func (e *GroupMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberRole(s)
	case string:
		*e = GroupMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberRole: %T", src)
	}
	return nil
}

type NullGroupMemberRole struct {
	GroupMemberRole GroupMemberRole `json:"group_member_role"`
	Valid           bool            `json:"valid"` // Valid is true if GroupMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberRole), nil
}

type GroupMemberStatus string

const (
	GroupMemberStatusInvited  GroupMemberStatus = "invited"
	GroupMemberStatusAccepted GroupMemberStatus = "accepted"
)

func (e *GroupMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberStatus(s)
	case string:
		*e = GroupMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberStatus: %T", src)
	}
	return nil
}

type NullGroupMemberStatus struct {
	GroupMemberStatus GroupMemberStatus `json:"group_member_status"`
	Valid             bool              `json:"valid"` // Valid is true if GroupMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberStatus), nil
}

type Bookmark struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	TweetID   int32     `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Follow struct {
	ID             int32     `json:"id"`
	UserID         int32     `json:"user_id"`
	FollowedUserID int32     `json:"followed_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Group struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupMember struct {
	ID         int32             `json:"id"`
	GroupID    int32             `json:"group_id"`
	UserID     int32             `json:"user_id"`
	Role       GroupMemberRole   `json:"role"`
	Status     GroupMemberStatus `json:"status"`
	InvitedBy  sql.NullInt32     `json:"invited_by"`
	AcceptedAt sql.NullTime      `json:"accepted_at"`
	CreatedAt  time.Time         `json:"created_at"`
}

type Like struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	TweetID   int32     `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	GroupID   int32     `json:"group_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Retweet struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	TweetID   int32     `json:"tweet_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Tweet struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserActivation struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expired_at"`
	CreatedAt time.Time `json:"created_at"`
}
