// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const countUnreadNotificationsByUserID = `-- name: CountUnreadNotificationsByUserID :one
SELECT COUNT(*)::bigint AS unread_count
FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotificationsByUserID(ctx context.Context, userID int32) (int64, error) {
	row := q.queryRow(ctx, q.countUnreadNotificationsByUserIDStmt, countUnreadNotificationsByUserID, userID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  user_id,
  actor_id,
  type,
  tweet_id,
  comment_id
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, actor_id, type, tweet_id, comment_id, is_read, read_at, created_at
`

type CreateNotificationParams struct {
	UserID    int32         `json:"user_id"`
	ActorID   int32         `json:"actor_id"`
	Type      string        `json:"type"`
	TweetID   sql.NullInt32 `json:"tweet_id"`
	CommentID sql.NullInt32 `json:"comment_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.queryRow(ctx, q.createNotificationStmt, createNotification,
		arg.UserID,
		arg.ActorID,
		arg.Type,
		arg.TweetID,
		arg.CommentID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.Type,
		&i.TweetID,
		&i.CommentID,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsByUserIDWithCursor = `-- name: GetNotificationsByUserIDWithCursor :many
SELECT id, user_id, actor_id, type, tweet_id, comment_id, is_read, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND (CASE WHEN $2 = 0 THEN true ELSE id < $2 END)
ORDER BY id DESC
LIMIT $3
`

type GetNotificationsByUserIDWithCursorParams struct {
	UserID  int32       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetNotificationsByUserIDWithCursor(ctx context.Context, arg GetNotificationsByUserIDWithCursorParams) ([]Notification, error) {
	rows, err := q.query(ctx, q.getNotificationsByUserIDWithCursorStmt, getNotificationsByUserIDWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.Type,
			&i.TweetID,
			&i.CommentID,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
