// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserActivation(ctx context.Context, arg CreateUserActivationParams) (UserActivation, error)
	DeleteTweet(ctx context.Context, arg DeleteTweetParams) error
	DeleteUserActivation(ctx context.Context, token string) error
	GetAllTweets(ctx context.Context, limit int32) ([]Tweet, error)
	GetTweetByID(ctx context.Context, id int32) (Tweet, error)
	GetTweetsByUserID(ctx context.Context, userID int32) ([]Tweet, error)
	GetUserActivationByToken(ctx context.Context, token string) (UserActivation, error)
	UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) error
}

var _ Querier = (*Queries)(nil)
