// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountLikesByTweetID(ctx context.Context, tweetID int32) (int64, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error)
	CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserActivation(ctx context.Context, arg CreateUserActivationParams) (UserActivation, error)
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeleteTweet(ctx context.Context, arg DeleteTweetParams) error
	DeleteUserActivation(ctx context.Context, token string) error
	ExistsLike(ctx context.Context, arg ExistsLikeParams) (bool, error)
	GetAllTweets(ctx context.Context, limit int32) ([]Tweet, error)
	GetTweetByID(ctx context.Context, id int32) (Tweet, error)
	GetTweetsByUserID(ctx context.Context, userID int32) ([]Tweet, error)
	GetUserActivationByToken(ctx context.Context, token string) (UserActivation, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) error
}

var _ Querier = (*Queries)(nil)
