// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retweets.sql

package db

import (
	"context"
)

const countRetweetsByTweetID = `-- name: CountRetweetsByTweetID :one
SELECT COUNT(*)::bigint AS retweet_count
FROM retweets
WHERE tweet_id = $1
`

func (q *Queries) CountRetweetsByTweetID(ctx context.Context, tweetID int32) (int64, error) {
	row := q.queryRow(ctx, q.countRetweetsByTweetIDStmt, countRetweetsByTweetID, tweetID)
	var retweet_count int64
	err := row.Scan(&retweet_count)
	return retweet_count, err
}

const createRetweet = `-- name: CreateRetweet :one
INSERT INTO retweets (
  user_id,
  tweet_id
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, tweet_id) DO NOTHING
RETURNING id, user_id, tweet_id, created_at
`

type CreateRetweetParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) CreateRetweet(ctx context.Context, arg CreateRetweetParams) (Retweet, error) {
	row := q.queryRow(ctx, q.createRetweetStmt, createRetweet, arg.UserID, arg.TweetID)
	var i Retweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TweetID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRetweet = `-- name: DeleteRetweet :exec
DELETE FROM retweets
WHERE user_id = $1 AND tweet_id = $2
`

type DeleteRetweetParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) DeleteRetweet(ctx context.Context, arg DeleteRetweetParams) error {
	_, err := q.exec(ctx, q.deleteRetweetStmt, deleteRetweet, arg.UserID, arg.TweetID)
	return err
}

const existsRetweet = `-- name: ExistsRetweet :one
SELECT EXISTS(
  SELECT 1
  FROM retweets
  WHERE user_id = $1 AND tweet_id = $2
) AS exists
`

type ExistsRetweetParams struct {
	UserID  int32 `json:"user_id"`
	TweetID int32 `json:"tweet_id"`
}

func (q *Queries) ExistsRetweet(ctx context.Context, arg ExistsRetweetParams) (bool, error) {
	row := q.queryRow(ctx, q.existsRetweetStmt, existsRetweet, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserRetweetsWithCursor = `-- name: GetUserRetweetsWithCursor :many
SELECT id, user_id, tweet_id, created_at
FROM retweets
WHERE user_id = $1
  AND (CASE WHEN $2 = 0 THEN true ELSE id < $2 END)
ORDER BY id DESC
LIMIT $3
`

type GetUserRetweetsWithCursorParams struct {
	UserID  int32       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetUserRetweetsWithCursor(ctx context.Context, arg GetUserRetweetsWithCursorParams) ([]Retweet, error) {
	rows, err := q.query(ctx, q.getUserRetweetsWithCursorStmt, getUserRetweetsWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Retweet{}
	for rows.Next() {
		var i Retweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TweetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
