// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tweets.sql

package db

import (
	"context"
)

const createTweet = `-- name: CreateTweet :one
INSERT INTO tweets (
  user_id,
  content
) VALUES (
  $1, $2
) RETURNING id, user_id, content, created_at, updated_at
`

type CreateTweetParams struct {
	UserID  int32  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error) {
	row := q.queryRow(ctx, q.createTweetStmt, createTweet, arg.UserID, arg.Content)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTweet = `-- name: DeleteTweet :exec
DELETE FROM tweets
WHERE id = $1 AND user_id = $2
`

type DeleteTweetParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteTweet(ctx context.Context, arg DeleteTweetParams) error {
	_, err := q.exec(ctx, q.deleteTweetStmt, deleteTweet, arg.ID, arg.UserID)
	return err
}

const getAllTweets = `-- name: GetAllTweets :many
SELECT id, user_id, content, created_at, updated_at
FROM tweets
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetAllTweets(ctx context.Context, limit int32) ([]Tweet, error) {
	rows, err := q.query(ctx, q.getAllTweetsStmt, getAllTweets, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tweet{}
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTweetByID = `-- name: GetTweetByID :one
SELECT id, user_id, content, created_at, updated_at
FROM tweets
WHERE id = $1
`

func (q *Queries) GetTweetByID(ctx context.Context, id int32) (Tweet, error) {
	row := q.queryRow(ctx, q.getTweetByIDStmt, getTweetByID, id)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTweetsByUserID = `-- name: GetTweetsByUserID :many
SELECT id, user_id, content, created_at, updated_at
FROM tweets
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTweetsByUserID(ctx context.Context, userID int32) ([]Tweet, error) {
	rows, err := q.query(ctx, q.getTweetsByUserIDStmt, getTweetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tweet{}
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
