// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tweets.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createTweet = `-- name: CreateTweet :one
INSERT INTO tweets (
  user_id,
  content
) VALUES (
  $1, $2
) RETURNING id, user_id, content, image_url, created_at, updated_at
`

type CreateTweetParams struct {
	UserID  int32  `json:"user_id"`
	Content string `json:"content"`
}

type CreateTweetRow struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) (CreateTweetRow, error) {
	row := q.queryRow(ctx, q.createTweetStmt, createTweet, arg.UserID, arg.Content)
	var i CreateTweetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTweetWithImage = `-- name: CreateTweetWithImage :one
INSERT INTO tweets (
  user_id,
  content,
  image_url
) VALUES (
  $1, $2, $3
) RETURNING id, user_id, content, image_url, created_at, updated_at
`

type CreateTweetWithImageParams struct {
	UserID   int32          `json:"user_id"`
	Content  string         `json:"content"`
	ImageUrl sql.NullString `json:"image_url"`
}

type CreateTweetWithImageRow struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTweetWithImage(ctx context.Context, arg CreateTweetWithImageParams) (CreateTweetWithImageRow, error) {
	row := q.queryRow(ctx, q.createTweetWithImageStmt, createTweetWithImage, arg.UserID, arg.Content, arg.ImageUrl)
	var i CreateTweetWithImageRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTweet = `-- name: DeleteTweet :exec
DELETE FROM tweets
WHERE id = $1 AND user_id = $2
`

type DeleteTweetParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteTweet(ctx context.Context, arg DeleteTweetParams) error {
	_, err := q.exec(ctx, q.deleteTweetStmt, deleteTweet, arg.ID, arg.UserID)
	return err
}

const getAllTweets = `-- name: GetAllTweets :many
SELECT id, user_id, content, image_url, created_at, updated_at
FROM tweets
ORDER BY created_at DESC
LIMIT $1
`

type GetAllTweetsRow struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetAllTweets(ctx context.Context, limit int32) ([]GetAllTweetsRow, error) {
	rows, err := q.query(ctx, q.getAllTweetsStmt, getAllTweets, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTweetsRow{}
	for rows.Next() {
		var i GetAllTweetsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTweetByID = `-- name: GetTweetByID :one
SELECT id, user_id, content, image_url, created_at, updated_at
FROM tweets
WHERE id = $1
`

type GetTweetByIDRow struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetTweetByID(ctx context.Context, id int32) (GetTweetByIDRow, error) {
	row := q.queryRow(ctx, q.getTweetByIDStmt, getTweetByID, id)
	var i GetTweetByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTweetsByIDs = `-- name: GetTweetsByIDs :many
SELECT id, user_id, content, image_url, created_at, updated_at
FROM tweets
WHERE id = ANY($1::int[])
`

type GetTweetsByIDsRow struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetTweetsByIDs(ctx context.Context, dollar_1 []int32) ([]GetTweetsByIDsRow, error) {
	rows, err := q.query(ctx, q.getTweetsByIDsStmt, getTweetsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTweetsByIDsRow{}
	for rows.Next() {
		var i GetTweetsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTweetsByUserID = `-- name: GetTweetsByUserID :many
SELECT id, user_id, content, image_url, created_at, updated_at
FROM tweets
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetTweetsByUserIDRow struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetTweetsByUserID(ctx context.Context, userID int32) ([]GetTweetsByUserIDRow, error) {
	rows, err := q.query(ctx, q.getTweetsByUserIDStmt, getTweetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTweetsByUserIDRow{}
	for rows.Next() {
		var i GetTweetsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTweetsByUserIDWithCursor = `-- name: GetTweetsByUserIDWithCursor :many
SELECT id, user_id, content, image_url, created_at, updated_at
FROM tweets
WHERE user_id = $1
  AND (CASE WHEN $2 = 0 THEN true ELSE id < $2 END)
ORDER BY id DESC
LIMIT $3
`

type GetTweetsByUserIDWithCursorParams struct {
	UserID  int32       `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
}

type GetTweetsByUserIDWithCursorRow struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetTweetsByUserIDWithCursor(ctx context.Context, arg GetTweetsByUserIDWithCursorParams) ([]GetTweetsByUserIDWithCursorRow, error) {
	rows, err := q.query(ctx, q.getTweetsByUserIDWithCursorStmt, getTweetsByUserIDWithCursor, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTweetsByUserIDWithCursorRow{}
	for rows.Next() {
		var i GetTweetsByUserIDWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
