// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package db

import (
	"context"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
  user_id,
  name,
  bio,
  image_url,
  location
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, user_id, name, bio, image_url, location, created_at, updated_at
`

type CreateUserProfileParams struct {
	UserID   int32  `json:"user_id"`
	Name     string `json:"name"`
	Bio      string `json:"bio"`
	ImageUrl string `json:"image_url"`
	Location string `json:"location"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.queryRow(ctx, q.createUserProfileStmt, createUserProfile,
		arg.UserID,
		arg.Name,
		arg.Bio,
		arg.ImageUrl,
		arg.Location,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.ImageUrl,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT id, user_id, name, bio, image_url, location, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID int32) (UserProfile, error) {
	row := q.queryRow(ctx, q.getUserProfileByUserIDStmt, getUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.ImageUrl,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles
SET name = $2, bio = $3, image_url = $4, location = $5, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, name, bio, image_url, location, created_at, updated_at
`

type UpdateUserProfileParams struct {
	UserID   int32  `json:"user_id"`
	Name     string `json:"name"`
	Bio      string `json:"bio"`
	ImageUrl string `json:"image_url"`
	Location string `json:"location"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile,
		arg.UserID,
		arg.Name,
		arg.Bio,
		arg.ImageUrl,
		arg.Location,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.ImageUrl,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
